apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: jobs
build:
  artifacts:
  - image: jobs
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes/*.yaml
